# Generated by Django 4.0.1 on 2022-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_auto_20220108_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='description',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='text',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('OPEN', 'Открыто'), ('CLOSED', 'Закрыто')], default='OPEN', verbose_name='Cтатус'),
        ),
    ]
