# Generated by Django 4.0.1 on 2022-02-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_remove_advertisement_description_advertisement_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='text',
            new_name='descriptions',
        ),
    ]
